"""message

Revision ID: 285b47b91e13
Revises: f7742e31928b
Create Date: 2024-07-01 12:21:05.825595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285b47b91e13'
down_revision = 'f7742e31928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
